//settings: head:设置项名称，type:设置项类型（1：输入类型（数字）；2：选择类型；3：输入类型（字符串）），option:选择内容项
var f_setList = [
  {
    'id': 0,
    'name': '基本设置',
    'show': true,
    'items': [
      {
        'id': 0,
        'head': '从机地址',
        'type': 'text',
        'unit': null,
        'variable': 'slaveAddr',
        'value': 1,
        'baseVale': 1,
        'option': null,
        'tips': '1-247',
        'textType': 'digit',
        'backupValue': 1,
      },
      {
        'id': 1,
        'head': '测量模式',
        'type': 'select',
        'unit': null,
        'variable': 'MeasureMode',
        'value': '正常',
        'baseVale': '正常',
        'option': ['正常', '演示'],
        'tips': null,
        'backupValue': '正常',
      },
      {
        'id': 2,
        'head': '最大流速',
        'type': 'text',
        'unit': 'm/s',
        'variable': 'maxFlow',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 3,
        'head': '最小流速',
        'type': 'text',
        'unit': 'm/s',
        'variable': 'minFlow',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 4,
        'head': '跟踪速度',
        'type': 'text',
        'unit': 'm/s2',
        'variable': 'trackAcceleratedSpeed',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 5,
        'head': '清零定时器',
        'type': 'text',
        'unit': '',
        'variable': 'zeroingTimer',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(0-100)',
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 6,
        'head': '复位定时器',
        'type': 'text',
        'unit': null,
        'variable': 'dampingTime',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(0-600)',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 7,
        'head': '复位余量',
        'type': 'text',
        'unit': 'dB',
        'variable': 'outputSmooth',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(0-20)',
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 8,
        'head': 'TVT余量',
        'type': 'text',
        'unit': '',
        'variable': 'thresholdMargin',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '',
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 9,
        'head': '输出平滑',
        'type': 'text',
        'unit': null,
        'variable': 'outputAver',
        'value': 1,
        'baseVale': 1,
        'option': null,
        'tips': '(1-100)',
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
    ],
  },
  {
    'id': 1,
    'name': '蓝牙设置',
    'show': true,
    'items': [
      {
        'id': 0,
        'head': '蓝牙名称',
        'type': 'text',
        'unit': null,
        'variable': 'bleName',
        'value': '',
        'baseVale': '',
        'option': null,
        'tips': null,
        'initSend': true,
        'textType': 'text'
      },
      {
        'id': 1,
        'head': '蓝牙密码',
        'type': 'text',
        'unit': null,
        'variable': 'blePincode',
        'value': '',
        'baseVale': '',
        'option': null,
        'tips': null,
        'initSend': true,
        'textType': 'digit'
      }
    ],
  },
];
  
module.exports = {
  f_setList: f_setList
}