//settings: head:设置项名称，type:设置项类型（1：输入类型（数字）；2：选择类型；3：输入类型（字符串）），option:选择内容项
var language = require('./languageUtils');
var lang = language._lang();
var f_setList = [
  {
    'id': 0,
    'name': '基本设置',
    'show': true,
    'items': [
      {
        'id': 0,
        'head': '从机地址',
        'type': 'text',
        'unit': null,
        'variable': 'slaveAddr',
        'value': 1,
        'baseVale': 1,
        'option': null,
        'tips': '1-247',
        'textType': 'digit',
        'backupValue': 1,
      },
      {
        'id': 1,
        'head': '测量模式',
        'type': 'select',
        'unit': null,
        'variable': 'MeasureMode',
        'value': '正常',
        'baseVale': '正常',
        'option': ['正常', '演示'],
        'tips': null,
        'backupValue': '正常',
      },
      {
        'id': 2,
        'head': '最大流速',
        'type': 'text',
        'unit': 'm/s',
        'variable': 'maxFlow',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 3,
        'head': '最小流速',
        'type': 'text',
        'unit': 'm/s',
        'variable': 'minFlow',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 4,
        'head': '跟踪速度',
        'type': 'text',
        'unit': 'm/s2',
        'variable': 'trackAcceleratedSpeed',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 5,
        'head': '清零定时器',
        'type': 'text',
        'unit': '',
        'variable': 'zeroingTimer',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(0-100)',
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 6,
        'head': '复位定时器',
        'type': 'text',
        'unit': null,
        'variable': 'dampingTime',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(0-100)',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 7,
        'head': '复位余量',
        'type': 'text',
        'unit': 'dB',
        'variable': 'outputSmooth',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(0-20)',
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 8,
        'head': 'TVT余量',
        'type': 'text',
        'unit': '',
        'variable': 'thresholdMargin',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '',
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 9,
        'head': '输出平滑',
        'type': 'text',
        'unit': null,
        'variable': 'outputAver',
        'value': 1,
        'baseVale': 1,
        'option': null,
        'tips': '(1-100)',
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
    ],
  },
  {
    'id': 1,
    'name': '蓝牙设置',
    'show': true,
    'items': [
      {
        'id': 0,
        'head': '蓝牙名称',
        'type': 'text',
        'unit': null,
        'variable': 'bleName',
        'value': '',
        'baseVale': '',
        'option': null,
        'tips': null,
        'initSend': true,
        'textType': 'text'
      },
      {
        'id': 1,
        'head': '蓝牙密码',
        'type': 'text',
        'unit': null,
        'variable': 'blePincode',
        'value': '',
        'baseVale': '',
        'option': null,
        'tips': null,
        'initSend': true,
        'textType': 'digit'
      }
    ],
  },
  {
    'id': 2,
    'name': '流量相关',
    'show': true,
    'items': [
      {
        'id': 0,
        'head': '安装偏移',
        'type': 'text',
        'unit': 'm',
        'variable': 'installationOffset',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 1,
        'head': '左边坡角度',
        'type': 'text',
        'unit': '°',
        'variable': 'riveAngleLeft',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 2,
        'head': '右边坡角度',
        'type': 'text',
        'unit': '°',
        'variable': 'riveAngleRight',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 3,
        'head': '河道底宽度',
        'type': 'text',
        'unit': 'm',
        'variable': 'riverBottomWidth',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 4,
        'head': '流速偏移',
        'type': 'text',
        'unit': 'm',
        'variable': 'velOffset',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': '(0-0.1)',
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 5,
        'head': '河流流量',
        'type': 'text',
        'unit': 'm³/s',
        'variable': 'riverDischarge',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
      {
        'id': 6,
        'head': '累计流量',
        'type': 'text',
        'unit': 'm³',
        'variable': 'riverDischargeTotal',
        'value': 0.0,
        'baseVale': 0.0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'textType': 'digit',
        'backupValue': 0,
      },
    ],
  },
  {
    'id': 3,
    'name': '水位计相关',
    'show': true,
    'items': [
      {
        'id': 0,
        'head': '容器类型',
        'type': 'select',
        'unit': null,
        'variable': 'appType',
        'value': '河流',
        'baseVale': '河流',
        'option': [lang['河流'], lang['潮汐'], lang['井'], lang['演示'], lang['水箱']],
        'tips': null,
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 1,
        'head': '测量类型',
        'type': 'select',
        'unit': null,
        'variable': 'meaType',
        'value': '物位',
        'baseVale': '物位',
        'option': [lang['物位'], lang['空高'], lang['距离']],
        'tips': null,
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 2,
        'head': '阻尼滤波',
        'type': 'text',
        'unit': 's',
        'variable': 'dampingTimeWater',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(0-600)',
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 3,
        'head': '平均次数',
        'type': 'text',
        'unit': null,
        'variable': 'averageTimes',
        'value': 1,
        'baseVale': 1,
        'option': null,
        'tips': '(1-100)',
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 4,
        'head': '丢波时距离输出',
        'type': 'select',
        'unit': null,
        'variable': 'loseWaveDistance',
        'value': '最大量程',
        'baseVale': '最大量程',
        'option': ['最大量程', '不变', '最小量程'],
        'tips': null,
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 5,
        'head': '连续丢波时间',
        'type': 'text',
        'unit': 's',
        'variable': 'continueLoseTime',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(0-1000)',
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 6,
        'head': '测量时间间隔',
        'type': 'text',
        'unit': 'ms',
        'variable': 'measureInterval',
        'value': 100,
        'baseVale': 100,
        'option': null,
        'tips': '(≥100)',
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 7,
        'head': '低位调整',
        'type': 'text',
        'unit': 'm',
        'variable': 'lowAdjustment',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 8,
        'head': '高位调整',
        'type': 'text',
        'unit': 'm',
        'variable': 'highAdjustment',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 9,
        'head': '盲区范围',
        'type': 'text',
        'unit': 'm',
        'variable': 'blindAreaRange',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 10,
        'head': '量程设定',
        'type': 'text',
        'unit': 'm',
        'variable': 'rangeRange',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': null,
        'frameType': 'float',
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 11,
        'head': '响应速度上',
        'type': 'text',
        'unit': 'm/min',
        'variable': 'feedRate',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(0-300)',
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 12,
        'head': '响应速度下',
        'type': 'text',
        'unit': 'm/min',
        'variable': 'dischargeRate',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(0-300)',
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 13,
        'head': '零点偏移',
        'type': 'text',
        'unit': 'm',
        'variable': 'sensorCorOffset',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': '(-1-10)',
        'frameType': 'float',
        'initSend': true,
        'textType': 'text'
      },
      {
        'id': 14,
        'head': '阈值余量',
        'type': 'text',
        'unit': 'dB',
        'variable': 'thresholdMarginWater',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': null,
        'initSend': true,
        'textType': 'digit'
      },
      {
        'id': 15,
        'head': '输出平滑',
        'type': 'text',
        'unit': null,
        'variable': 'outSmoothWater',
        'value': 0,
        'baseVale': 0,
        'option': null,
        'tips': null,
        'initSend': true,
        'textType': 'digit'
      },
    ],
  },
];
  
module.exports = {
  f_setList: f_setList
}