//settings: head:设置项名称，type:设置项类型（1：输入类型（数字）；2：选择类型；3：输入类型（字符串）），option:选择内容项
var lang = require('./languageUtils');

var _lang = lang._lang();

var w_setList = [
  {
    'id': 0,
    'head': '从机地址',
    'type': 'text',
    'unit': null,
    'variable': 'slaveAddr',
    'value': 1,
    'baseVale': 1,
    'option': null,
    'tips': '(1-247)',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 1,
    'head': '容器类型',
    'type': 'select',
    'unit': null,
    'variable': 'appType',
    'value': '河流',
    'baseVale': '河流',
    'option': ['河流', '潮汐', '井', '演示', '水箱'],
    'tips': null,
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 2,
    'head': '测量类型',
    'type': 'select',
    'unit': null,
    'variable': 'meaType',
    'value': '物位',
    'baseVale': '物位',
    'option': ['物位', '空高', '距离'],
    'tips': null,
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 3,
    'head': '阻尼滤波',
    'type': 'text',
    'unit': 's',
    'variable': 'dampingTime',
    'value': 0,
    'baseVale': 0,
    'option': null,
    'tips': '(0-600)',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 4,
    'head': '平均次数',
    'type': 'text',
    'unit': null,
    'variable': 'averageTimes',
    'value': 1,
    'baseVale': 1,
    'option': null,
    'tips': '(1-100)',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 5,
    'head': '丢波时距离输出',
    'type': 'select',
    'unit': null,
    'variable': 'loseWaveDistance',
    'value': '最大量程',
    'baseVale': '最大量程',
    'option': ['最大量程', '不变', '最小量程'],
    'tips': null,
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 6,
    'head': '连续丢波时间',
    'type': 'text',
    'unit': 's',
    'variable': 'continueLoseTime',
    'value': 0,
    'baseVale': 0,
    'option': null,
    'tips': '(0-1000)',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 7,
    'head': '测量时间间隔',
    'type': 'text',
    'unit': 'ms',
    'variable': 'measureInterval',
    'value': 100,
    'baseVale': 100,
    'option': null,
    'tips': '(≥100)',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 8,
    'head': '低位调整',
    'type': 'text',
    'unit': 'm',
    'variable': 'lowAdjustment',
    'value': 0,
    'baseVale': 0,
    'option': null,
    'tips': null,
    'frameType': 'float',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 9,
    'head': '高位调整',
    'type': 'text',
    'unit': 'm',
    'variable': 'highAdjustment',
    'value': 0,
    'baseVale': 0,
    'option': null,
    'tips': null,
    'frameType': 'float',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 10,
    'head': '盲区范围',
    'type': 'text',
    'unit': 'm',
    'variable': 'blindAreaRange',
    'value': 0,
    'baseVale': 0,
    'option': null,
    'tips': null,
    'frameType': 'float',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 11,
    'head': '量程设定',
    'type': 'text',
    'unit': 'm',
    'variable': 'rangeRange',
    'value': 0,
    'baseVale': 0,
    'option': null,
    'tips': null,
    'frameType': 'float',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 12,
    'head': '进料速率',
    'type': 'text',
    'unit': 'm/min',
    'variable': 'feedRate',
    'value': 0,
    'baseVale': 0,
    'option': null,
    'tips': '(0-300)',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 13,
    'head': '出料速率',
    'type': 'text',
    'unit': 'm/min',
    'variable': 'dischargeRate',
    'value': 0,
    'baseVale': 0,
    'option': null,
    'tips': '(0-300)',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 14,
    'head': '传感器修正偏移',
    'type': 'text',
    'unit': 'm',
    'variable': 'sensorCorOffset',
    'value': 0,
    'baseVale': 0,
    'option': null,
    'tips': '(-1-10)',
    'frameType': 'float',
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 15,
    'head': '阈值余量',
    'type': 'text',
    'unit': 'dB',
    'variable': 'thresholdMargin',
    'value': 0,
    'baseVale': 0,
    'option': null,
    'tips': null,
    'initSend': true,
    'textType': 'digit'
  },
  {
    'id': 16,
    'head': '蓝牙名称',
    'type': 'text',
    'unit': null,
    'variable': 'bleName',
    'value': '',
    'baseVale': '',
    'option': null,
    'tips': null,
    'initSend': true,
    'textType': 'text'
  },
  {
    'id': 17,
    'head': '蓝牙密码',
    'type': 'text',
    'unit': null,
    'variable': 'blePincode',
    'value': '',
    'baseVale': '',
    'option': null,
    'tips': null,
    'initSend': true,
    'textType': 'digit'
  }
];

module.exports = {
  w_setList: w_setList
}